steps:
  # Check if package-lock.json has changed
  - id: 'Check package-lock.json changes'
    name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: bash
    args:
      - '-c'
      - |
        if gsutil stat gs://${PROJECT_ID}-cache-dependencies/package-lock.json; then
          gsutil cp gs://${PROJECT_ID}-cache-dependencies/package-lock.json old-package-lock.json
          if cmp -s package-lock.json old-package-lock.json; then
            echo "false" >> /workspace/check.txt
          else
            echo "true" >> /workspace/check.txt
          fi
        else
          echo "true" >> /workspace/check.txt
        fi

  - id: 'Restoring NPM modules cache'
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - '-c'
      - |
        gsutil cp gs://${PROJECT_ID}-cache-dependencies/cache/node-modules.tgz node-modules.tgz || exit 0
        tar -zxf node-modules.tgz --directory /workspace || echo "No cache found"

  - id: 'Installing NPM dependencies'
    name: 'node:$_NODE_VERSION'
    entrypoint: npm
    args:
      - ci

  - id: 'Save npm cache'
    name: 'gcr.io/cloud-builders/gsutil'
    waitFor: [ 'Installing NPM dependencies' ]
    entrypoint: bash
    args:
      - '-c'
      - |
          tar -zcf node-modules.tgz ./node_modules
          gsutil cp node_modules gs://${PROJECT_ID}-cache-dependencies/node_modules.tgz
          gsutil cp package-lock.json gs://${PROJECT_ID}-cache-dependencies/package-lock.json
#        if [ "$(cat /workspace/check.txt)" == "true" ]; then
#        fi




  #  - name: 'gcr.io/$PROJECT_ID/save_cache'
  #    id: 'Saving .npm cache'
  #    args:
  #      - --bucket=gs://${PROJECT_ID}_cloudbuild
  #      - --key=npm-build-cache-$( checksum package.json )-$( checksum package-lock.json )
  #      - --path=.npm
  #      - --no-clobber
  #    waitFor: [ 'Installing NPM dependencies' ]

  # Build
  - name: 'node:$_NODE_VERSION'
    entrypoint: npm
    args: [ 'run', 'build' ]
    # Deploy
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: [ 'deploy', '--only=hosting' ]

options:
  machineType: 'N1_HIGHCPU_8'
