steps:
  # Install
  - name: 'gcr.io/$PROJECT_ID/restore_cache'
    id: 'Restoring NPM modules cache'
    args:
      - --bucket=gs://${PROJECT_ID}_cloudbuild
      - --key=npm-build-cache-$( checksum pnmp-lock.yaml )
      - --key_fallback=npm-build-cache-
      - --path=node_modules

  - name: 'node:$_NODE_VERSION'
    entrypoint: pnpm
    id: 'Installing NPM dependencies'
    args:
      - install
      - --frozen-lockfile

  - name: 'gcr.io/$PROJECT_ID/save_cache'
    id: 'Saving .npm cache'
    args:
      - --bucket=gs://${PROJECT_ID}_cloudbuild
      - --key=npm-build-cache-$( checksum pnmp-lock.yaml )
      - --path=node_modules
      - --no-clobber
    waitFor: [ 'Installing NPM dependencies' ]

  # Build
  - name: 'node:$_NODE_VERSION'
    entrypoint: pnpm
    args: [ 'run', 'build' ]
    # Deploy
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: [ 'deploy', '--only=hosting' ]

options:
  machineType: 'N1_HIGHCPU_8'
