options:
  machineType: 'N1_HIGHCPU_8'

steps:
  # Step 1: Check if package-lock.json changed
  - id: 'Check package-lock.json changes'
    name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: bash
    volumes:
      - name: 'shared-volume'
        path: '/workspace/shared'
    args:
      - '-c'
      - |
        echo "_PACKAGE_LOCK_CHANGED=true" >> /workspace/shared/env.txt

  # Step 2: Load environment variables
  - id: 'Load environment variables'
    name: 'alpine:latest'
    entrypoint: sh
    volumes:
      - name: 'shared-volume'
        path: '/workspace/shared'
    args:
      - '-c'
      - 'source /workspace/shared/env.txt && env'

volumes:
  - name: 'shared-volume'
    path: '/workspace/shared'

  # Step 3: Restore deps
  - id: 'Restoring NPM modules cache'
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - '-c'
      - |
        if [ "$_PACKAGE_LOCK_CHANGED" == "false" ]; then
          gsutil cp gs://${PROJECT_ID}-cache-dependencies/cache/node-modules.tgz node-modules.tgz || exit 0
          tar -zxf node-modules.tgz --directory /workspace || exit 0
        fi

  # Step 4: Install deps
  #  - name: 'node:$_NODE_VERSION'
  #    entrypoint: npm
  #    id: 'Installing NPM dependencies'
  #    args:
  #      - ci
  #      - --no-audit
  ##    when:
  ##      condition: '"$_PACKAGE_LOCK_CHANGED" == "true"'

  # Step 4: Install deps
  - name: 'alpine:latest'
    entrypoint: sh
    id: 'Installing NPM dependencies'
    args:
      - '-c'
      - |
        if [ "$_PACKAGE_LOCK_CHANGED" == "true" ]; then
          npm ci --no-audit
        fi

  - id: 'Saving .npm cache'
    waitFor: [ 'Installing NPM dependencies' ]
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - '-c'
      - |
        if [ "$_PACKAGE_LOCK_CHANGED" == "true" ]; then
          tar -zcf node-modules.tgz ./node_modules
          gsutil cp node-modules.tgz gs://${PROJECT_ID}-cache-dependencies/cache/node-modules.tgz
        fi

  # Step 5: Build
  - name: 'node:$_NODE_VERSION'
    entrypoint: npm
    args: [ 'run', 'build' ]

    # Step 6: Deploy
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: [ 'deploy', '--only=hosting' ]
