steps:
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args:
#      - kms
#      - decrypt
#        --ciphertext-file=.env.enc
#        --plaintext-file=.env
#        --location=global
#        --keyring=cloudbuild
#        --key=cloudbuild-env


  # Install
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'functions'
    args: [ 'install' ]


    # Deploy
  - name: 'gcr.io/$PROJECT_ID/npm'
    args: [ 'run', 'deploy']
    dir: 'functions'
    secretEnv: ['FIREBASE_TOKEN']


#steps:
#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    args:
#      - gcloud
#      - functions
#      - deploy
#      - getWeather
#      - --region=europe-central2
#      - --source=functions/weather
#      - --trigger-http
#      - --runtime=nodejs18

