steps:
  # Install
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'functions'
    args: [ 'install' ]


    # Deploy
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: [ 'deploy', '--only=functions', '--token $FIREBASE_TOKEN' ]


#steps:
#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    args:
#      - gcloud
#      - functions
#      - deploy
#      - getWeather
#      - --region=europe-central2
#      - --source=functions/weather
#      - --trigger-http
#      - --runtime=nodejs18

